import { COLORS } from '~/styles'

export const TOAST_TYPES = {
  DEFAULT: 'DEFAULT',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
}

export const TOAST_COLORS = {
  DEFAULT: COLORS.BLACK_OP90,
  SUCCESS: COLORS.FRUIT_SALAD,
  WARNING: COLORS.GORSE,
  ERROR: COLORS.POMEGRANATE,
}
