import { COLORS } from '~/styles'

export const TOAST_TYPES = {
  DEFAULT: 'DEFAULT',
  SUCCESS: 'SUCCESS',
  WARNING: 'WARNING',
  ERROR: 'ERROR',
}

export const TOAST_COLORS = {
  DEFAULT: COLORS.BLACK_OP75,
  SUCCESS: COLORS.FRUIT_SALAD_OP90,
  WARNING: COLORS.GORSE_OP90,
  ERROR: COLORS.POMEGRANATE_OP90,
}
